# NLP SESI 9

In [1]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
glove_dict = {}

with open("glove.6B.100d.txt", "r", encoding="utf-8") as file:
    for line in file:
        values = line.split(" ")
        word = values[0]
        vectors = np.array(values[1:], dtype="float32")
        glove_dict[word] = vectors
        

In [3]:
# glove_dict["king"]
if "king" in glove_dict.keys():
    print(glove_dict["king"])

[-0.32307  -0.87616   0.21977   0.25268   0.22976   0.7388   -0.37954
 -0.35307  -0.84369  -1.1113   -0.30266   0.33178  -0.25113   0.30448
 -0.077491 -0.89815   0.092496 -1.1407   -0.58324   0.66869  -0.23122
 -0.95855   0.28262  -0.078848  0.75315   0.26584   0.3422   -0.33949
  0.95608   0.065641  0.45747   0.39835   0.57965   0.39267  -0.21851
  0.58795  -0.55999   0.63368  -0.043983 -0.68731  -0.37841   0.38026
  0.61641  -0.88269  -0.12346  -0.37928  -0.38318   0.23868   0.6685
 -0.43321  -0.11065   0.081723  1.1569    0.78958  -0.21223  -2.3211
 -0.67806   0.44561   0.65707   0.1045    0.46217   0.19912   0.25802
  0.057194  0.53443  -0.43133  -0.34311   0.59789  -0.58417   0.068995
  0.23944  -0.85181   0.30379  -0.34177  -0.25746  -0.031101 -0.16285
  0.45169  -0.91627   0.64521   0.73281  -0.22752   0.30226   0.044801
 -0.83741   0.55006  -0.52506  -1.7357    0.4751   -0.70487   0.056939
 -0.7132    0.089623  0.41394  -1.3363   -0.61915  -0.33089  -0.52881
  0.16483  -0.98878

In [4]:
keys = list(glove_dict.keys())
values = np.array(list(glove_dict.values()))
values

array([[-0.038194, -0.24487 ,  0.72812 , ..., -0.1459  ,  0.8278  ,
         0.27062 ],
       [-0.10767 ,  0.11053 ,  0.59812 , ..., -0.83155 ,  0.45293 ,
         0.082577],
       [-0.33979 ,  0.20941 ,  0.46348 , ..., -0.23394 ,  0.47298 ,
        -0.028803],
       ...,
       [ 0.36088 , -0.16919 , -0.32704 , ...,  0.27139 , -0.29188 ,
         0.16109 ],
       [-0.10461 , -0.5047  , -0.49331 , ...,  0.42527 , -0.5125  ,
        -0.17054 ],
       [ 0.28365 , -0.6263  , -0.44351 , ...,  0.43678 , -0.82607 ,
        -0.15701 ]], dtype=float32)

In [19]:
vector = glove_dict["king"] - glove_dict["man"] + glove_dict["woman"]
vector

array([-0.10231996, -0.81294006,  0.10211003,  0.985924  ,  0.34218282,
        1.09095   , -0.48912996, -0.05616698, -0.21029997, -1.02996   ,
       -0.86851   ,  0.36786997,  0.01960999,  0.59259   , -0.23190099,
       -1.016919  , -0.01218399, -1.17194   , -0.52329   ,  0.60645   ,
       -0.98537004, -1.001028  ,  0.48913902,  0.630072  ,  0.58224   ,
        0.15908998,  0.43685   , -1.25351   ,  0.97054   , -0.065529  ,
        0.733763  ,  0.44219002,  1.2091839 ,  0.19698   , -0.15948   ,
        0.34364003, -0.46222997,  0.33772   ,  0.14792705, -0.24959502,
       -0.77093005,  0.522717  , -0.1283    , -0.91881   , -0.01755001,
       -0.44041002, -0.52656496,  0.33734798,  0.60639   , -0.45067   ,
       -0.04158002,  0.08408299,  1.31456   ,  0.67737997, -0.24316001,
       -2.071     , -0.60648996,  0.19710997,  0.63567   ,  0.07819998,
        0.49161002,  0.08171999,  0.70855707,  0.201938  ,  0.5155501 ,
       -0.23025298, -0.40473002,  0.39212003, -0.5093    , -0.13

In [20]:
similarity = cosine_similarity([vector], values).flatten()
similarity[0]

0.43393356

In [21]:
# ascending
top_idx = similarity.argsort()[-3:][::-1]
top_idx[0]

691

In [22]:
for idx in top_idx:
    print(f"keys: {keys[idx]}")
    print(f"score: {similarity[idx]}")
    print()

keys: king
score: 0.8551837205886841

keys: queen
score: 0.7834413647651672

keys: monarch
score: 0.6933801770210266



In [30]:
import pandas as pd
from nltk.tokenize import word_tokenize
from gensim.models import Word2Vec

In [24]:
df = pd.read_csv("mtsamples.csv")
df.head()

,medical_specialty,sample_name,transcription
0,Allergy / Immunology,Allergic Rhinitis,"SUBJECTIVE:, This 23-year-old white female pr..."
1,Bariatrics,Laparoscopic Gastric Bypass Consult - 2,"PAST MEDICAL HISTORY:, He has difficulty climb..."
2,Bariatrics,Laparoscopic Gastric Bypass Consult - 1,"HISTORY OF PRESENT ILLNESS: , I have seen ABC ..."
3,Cardiovascular / Pulmonary,2-D Echocardiogram - 1,"2-D M-MODE: , ,1. Left atrial enlargement wit..."
4,Cardiovascular / Pulmonary,2-D Echocardiogram - 2,1. The left ventricular cavity size and wall ...


In [ ]:
docs = df["transcription"].dropna().tolist()
docs

In [27]:
def get_tokens(sentence):
    return [token.lower() for token in word_tokenize(sentence)]

In [28]:
tokenized_docs = []
for sentence in docs:
    tokens = get_tokens(sentence)
    tokenized_docs.append(tokens)

In [31]:
skipgram = Word2Vec(
    tokenized_docs,
    min_count=1, 
    window=5, 
    vector_size=100,
    sg=1
    )
cbow = Word2Vec(
    tokenized_docs,
    min_count=1, 
    window=5, 
    vector_size=100
)

In [33]:
skipgram.wv["heart"]

array([-0.72567725,  0.43194842,  1.0507865 ,  0.06386781, -0.16877611,
        0.13331331,  0.85984135,  0.5052433 , -0.8868454 , -0.360244  ,
        0.170608  , -0.3284642 , -0.05468715, -0.1643602 ,  0.5702265 ,
        0.21858308,  0.14380845, -1.3308856 ,  0.5127058 , -0.97589946,
        0.44099155,  0.3011021 ,  0.28625563, -0.7368111 ,  0.42533296,
        0.56485754, -0.5114363 ,  0.16330011, -0.37690413,  0.29527193,
       -0.0659356 ,  0.48409528, -0.18538111, -0.9540416 ,  0.2936717 ,
        0.48370633,  0.02340366, -0.35976213,  0.35050943, -1.1580774 ,
       -0.4259505 , -0.25173244,  0.3659258 ,  0.04815008,  0.49678293,
       -0.07170964, -0.6727753 ,  0.01235814, -0.44429278, -0.06544598,
       -0.13243829, -0.91799366, -0.00773051, -0.17721203, -0.65474427,
        0.6556821 , -0.13083084, -0.16373551, -0.5884745 ,  0.12555365,
       -0.5639169 ,  0.04199084, -0.26525322, -0.22733591, -0.17130555,
        0.23444255, -0.18170862,  0.23258552, -0.28516316, -0.60

In [39]:
skipgram.wv.similarity("heart", "obesity")

0.46447062

In [40]:
skipgram.wv.most_similar("heart", topn=5)

[('rate', 0.7121200561523438),
 ('cardiac', 0.6830118894577026),
 ('regular', 0.6789926290512085),
 ('cardiovascular', 0.6581899523735046),
 ('irregularly', 0.6578125953674316)]

In [41]:
cbow.wv.similarity("heart", "obesity")

0.37993443

In [42]:
cbow.wv.most_similar("heart", topn=5)

[('cardiac', 0.7006416320800781),
 ('rhythm', 0.6787978410720825),
 ('regular', 0.6733874082565308),
 ('cardiovascular', 0.6719443202018738),
 ('irregularly', 0.6545469760894775)]